---
- name: Start thelounge
  ansible.builtin.systemd_service:
    name: thelounge
    state: started
    enabled: true

- name: Restart thelounge
  ansible.builtin.systemd_service:
    name: thelounge
    state: restarted
    daemon_reload: true
