---
- name: Configure Timezone to UTC
  community.general.timezone:
    name: Etc/UTC

# Install packages
- name: Install Packages
  ansible.builtin.include_tasks: packages.yml
  when:
    - common_install_packages | default(true) | bool

# Update SSH Config
- name: Sshd_config
  ansible.builtin.include_tasks: sshd_config.yml
  when:
    - common_sshd_config_file | default(true) | bool

# Update MOTD
- name: MOTD
  ansible.builtin.include_tasks: motd.yml
  when:
    - common_motd_info | default(true) | bool

# Install unattended ugprades
- name: Unattended-upgrades.yml
  ansible.builtin.include_tasks: unattended-upgrades.yml
  when:
    - common_unattended_upgrades | default(true) | bool
    - ansible_facts['os_family'] == "Debian"
