---
# Debian distributions
- name: Upgrade and install packages
  when: ansible_facts['os_family'] == "Debian"
  tags:
    - common_packages
  block:
    - name: Get list of installed packages before update
      ansible.builtin.shell: |
        dpkg-query -l | awk '/^ii/ {print "{\"name\": \"" $2 "\", \"version\": \"" $3 "\"}"}' | jq -s '.'
      register: packages_before
      changed_when: false

    - name: Upgrade dependencies
      ansible.builtin.apt:
        upgrade: true
        cache_valid_time: 43200

    - name: Install common packages
      ansible.builtin.apt:
        name: "{{ common_packages_to_install_debian }}"

    - name: Get list of installed packages after update
      ansible.builtin.shell: |
        dpkg-query -l | awk '/^ii/ {print "{\"name\": \"" $2 "\", \"version\": \"" $3 "\"}"}' | jq -s '.'
      register: packages_after
      changed_when: false

    - name: Create template file
      ansible.builtin.template:
        src: ubuntu_packages.j2
        dest: ../packageinfo-{{ ansible_date_time.iso8601 }}.txt
      vars:
        packages_before: "{{ packages_before }}"
        packages_after: "{{ packages_after }}"
      run_once: true
      delegate_to: localhost

    - name: Autoremove and Clean packages
      ansible.builtin.apt: { autoremove: true, clean: true }

## Redhat Distribution
- name: Upgrade and install packages
  when: ansible_facts['os_family'] == "RedHat"
  tags:
    - common_packages
  block:
    - name: Update repositories
      ansible.builtin.dnf:
        update_cache: true
      register: app_upgrade

    - name: Install Packages
      ansible.builtin.dnf:
        name: "{{ common_packages_to_install_redhat }}"
      register: app_install

    - name: Write a report about what has been done
      ansible.builtin.template:
        src: report.j2
        dest: ../report-{{ ansible_date_time.iso8601_micro }}.txt
      run_once: true
      delegate_to: localhost

    - name: Autoremove unneeded packages installed as dependencies
      ansible.builtin.dnf:
        autoremove: true
