---
- name: Build unattended-upgrades
  tags:
    - unattended
  when: ansible_facts['os_family'] is defined and ansible_facts['os_family'] == "Debian"
  block:
    - name: Install unattended-upgrades package
      ansible.builtin.apt:
        name: unattended-upgrades
        state: present

    - name: Enable unattended-upgrades
      ansible.builtin.command: dpkg-reconfigure -f noninteractive unattended-upgrades
      register: my_output
      changed_when: my_output.rc != 0

    - name: Copy unattended-upgrades configuration file
      ansible.builtin.copy:
        src: unattended-upgrades/50unattended-upgrades
        dest: /etc/apt/apt.conf.d/50unattended-upgrades
        owner: root
        group: root
        checksum: false
        mode: "0644"

    - name: Copy 20auto-upgrades file
      ansible.builtin.copy:
        src: unattended-upgrades/20auto-upgrades
        dest: /etc/apt/apt.conf.d/20auto-upgrades
        owner: root
        group: root
        checksum: false
        mode: "0644"

    - name: Ensure unattended-upgrades service is running
      ansible.builtin.systemd:
        name: unattended-upgrades
        state: started
        enabled: true