- name: Start wikijs
  ansible.builtin.systemd_service:
    name: wikijs
    state: started
    enabled: yes

- name: Restart wikijs
  ansible.builtin.systemd_service:
    name: wikijs
    state: restarted
    daemon_reload: yes