---
- name: Start ssh
  ansible.builtin.systemd_service:
    name: >
      {% if ansible_facts['os_family'] == "Debian" %}
      ssh
      {% elif ansible_facts['os_family'] == "RedHat" %}
      sshd
      {% endif %}
    state: started
    enabled: true

- name: Restart ssh
  ansible.builtin.systemd_service:
    name: >-
      {%- if ansible_facts['os_family'] == "Debian" -%} ssh{%- else -%} sshd{%- endif -%}
    state: restarted
    daemon_reload: true
