---
- name: Set authorized keys
  ansible.posix.authorized_key:
    user: root
    key: >-
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICRT+Y/OLV93J//KgATURLloYS8k9QFeXapAdx8AbnWZ illegal@legal
    state: present

- name: Prometheus-pve-exporter
  ansible.builtin.include_tasks: prometheus-pve-exporter.yml
  when:
    - prometheus_pve_exporter | default(true) | bool

- name: Create API Token
  ansible.builtin.import_tasks: generate_token.yml
  when: proxmox_enable_api_token | default(false)
