global:
  scrape_interval:     5s
  evaluation_interval: 5s

alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v1

scrape_configs:
  - job_name: 'nodeexporter'
    static_configs:
      - targets: ['nodeexporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'caddy'
    scheme: https
    static_configs:
      - targets: ['10.10.10.2:3000']
    tls_config:
      insecure_skip_verify: true

  - job_name: 'opnsense-nodeexporter'
    static_configs:
      - targets: ['opnsense.inside.lan:9100']