all:
  children:
    production:
      children:

        hypervisors:
          children:
            proxmox:
              hosts:
                proxmox.inside.lan: { proxmox.inside.lan }
              # vars: { common_install_packages: false, common_sshd_config_file: false } 

        docker:
          children:
            monitoring:
              hosts:
                dockerapp.inside.lan: { dockerapps.inside.lan }

        wikijs:
          hosts:
            wikijs.inside.lan: { wikijs.inside.lan }

        cloud:
          children:
            proxy:
              children:
                caddy:
                  hosts:
                    10.10.10.2:
            s2s_tunnel:
              children:
                oci_cloud:
                  hosts:
                    10.10.10.2:
                      ansible_user: "opc"
                      ansible_ssh_private_key_file: "~/.ssh/oci_wireguard"
                  vars: { wireguard_server: true, common_sshd_config_file: false }

        irc:
          hosts:
            thelounge.inside.lan: { thelounge.inside.lan }

        # influxdb:
        #   hosts:
        #     influxdb.inside.lan: { influxdb.inside.lan }

        pxe:
          hosts:
            pxe.inside.lan: { pxe.inside.lan }

        # freeipa:
        #   hosts:
        #     ipa.inside.lan: { ipa.inside.lan }

    development:
      children:
        testing:
          hosts:
            10.0.0.46:
              ansible_user: "rocky"
              ansible_ssh_private_key_file: "/home/illegal/.ssh/applications"
