---
- name: Start influxdb
  ansible.builtin.systemd_service:
    name: influxdb.service
    state: started
    enabled: true

- name: Restart influxdb
  ansible.builtin.systemd_service:
    name: influxdb.service
    state: restarted
    daemon_reload: true
