name: Gitleaks Pre-Commit Check

on:
  push:
    branches: [ "main", "dev", "release/*" ]
  pull_request:
    branches: [ "main", "dev", "release/*" ]

jobs:
  gitleaks-scan:
    name: Run Gitleaks Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Run Gitleaks
      uses: zricethezav/gitleaks-action@v1.3.0
      with:
        args: "--redact --path ." # you can specify additional Gitleaks arguments here

    - name: Check for Leaks
      run: |
        if gitleaks detect --path . --exit-code 1 --redact; then
          echo "No secrets detected."
        else
          echo "Secrets detected! Please address the issues and try again."
          exit 1
        fi
